package:
  name: correspondentia-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - correspondentia

about:
  home: https://github.com/BONSAMURAIS/correspondentia
  license: BSD License
  summary: 'Apply correspondence tables in various formats to Python data structures'
license_family: BSD
